### ISSUE TITLE
Create Prototype from existing mockup

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#1]
Figma. This is still rough, but will suffice for first prototype https://www.figma.com/file/G8essVjeMul3J5mKoxCMQF/spotlightpa-(INTERNAL)?node-id=0%3A1

**Notes**
- The mockup is for the about page. The hero and top-nav will eventually be global. 
- We will be creating individual pages for
    - Impact & Awards
    - Partners
    - Staff
    - Supporters
    - Mission
- However, the links on the page below the about copy will lead to that place on the page.
- The mockup has only two sections (Impact..., Partners), but we will have sections on the page for each of the other items.
- I have Work Sans font in there. Ignore that and use Raleway that is already there. (I just don't think the client's font choice is good, but we should stick with it though)
- When user clicks on "More Topics" a drawer should reveal below the hero and show several columns. See mockup for a very rough first draft. - topics should come from: https://www.spotlightpa.org/topics/

**Comment by AdamChlan** [comment]
@regisphilibert Believe I am going to need some assistance hiding the existing nav/footer from the new about page. Also I'm having trouble getting rid of the banner ad for the newsletter. When you get a chance, can we review? The branch is up to-date, and the page renders at /about/about-tnd

**Comment by regisphilibert** [comment]
@AdamChlan @budparr we have a working preview on cloudflare: https://spotlightpa-org.pages.dev/about/about-tnd/
