### ISSUE TITLE
Improve nav on mobile

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#11]
Should look like this screenshot (except that the search icon should be inline with text)
<img width="279" alt="Screen Shot 2022-05-23 at 1 31 07 PM" src="https://user-images.githubusercontent.com/115347/169875500-c2a27883-8d33-460e-8415-c06b5a89c4b2.png">

**Comment by AdamChlan** [comment]
@budparr @regisphilibert this has been addressed on our working branch
