### ISSUE TITLE
Make interior page sticky nav

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#12]
take existing internal about page nav (mid-way down the page on about landing) and make it stick when one navigates to the top. It should have the spotlight logo, but I'm not sure if we have one without the back background, so perhaps for now we just put in text and note that we need it.

<img width="1018" alt="Screen Shot 2022-05-23 at 1 51 37 PM" src="https://user-images.githubusercontent.com/115347/169878470-cf78c0f5-0bd3-4e7e-8ab8-2bf26f4c1d52.png">

note that on interior about pages, these will be page links, not on-page links

**Comment by AdamChlan** [comment]
@budparr I pushed up code for this. I believe I have it working as you requested but let me know.

**Comment by budparr** [comment]
Looks good. A bit less padding, and it should only be on internal about pages (sorry, that was not clear enough in my request). There's `about-tnd.md` and `about-tnd-internal.md.` The latter is the basis for the interior pages, the former for the about landing page.

cc @regisphilibert on that point. You all are welcome to change the structure, whatever, I just need a slightly different layout for interior about pages.

**Comment by AdamChlan** [comment]
Okay I pushed up the padding fix. @regisphilibert we can discuss the best way to use this component, and only have it be sticky on interior pages.

**Comment by budparr** [comment]
notes:
- [x] it looks like the logo is now showing all the time and it should only show when sticky
- [x] Can we go ahead and put the real logo in there? If there isn't a logo on white go ahead and use the one we have as a placeholder.
- [x] Please add the red support us button when sticky. Is should be justified over to the right with space between it and the rest.
- [x] Aggregate about page: Highlight the menu items (with background color change, black, ugh, I guess) as a user scrolls (we chatted about this this morning, but let me know if you need more clarification).
- [x] Interior about pages: Highlight the active menu items.

Thanks!

**Comment by regisphilibert** [comment]
@AdamChlan I'll take care of the last two checkboxes and hand it back to you.

**Comment by AdamChlan** [comment]
@budparr for the logo only being visible when sticky....I reserved a space for the logo when not sticky. if you'd prefer that space not be there, let me know. Then the nav items will shift right when nav is sticky.

**Comment by budparr** [comment]
Thank you. Yes, I do not want the logo to show except when the nav is sticky. 
I'd also like the "Support us" button back in the content area (where it was before) except when it's sticky. @regisphilibert says that would mean having two separate buttons, but I think that's okay.

**Comment by budparr** [comment]
Also we need to adjust the scroll targets on the main about page as they are obscuring the content.
<img width="793" alt="Screen Shot 2022-05-30 at 10 22 45 AM" src="https://user-images.githubusercontent.com/115347/171011936-f76e448c-2e7c-4846-9c5b-f97891165848.png">

**Comment by AdamChlan** [comment]
@budparr I just pushed up adjustments for the logo and support button, and scroll targets. The last thing we may need to clean up is how it behaves on mobile. Do we want sticky on mobile, or want to consider not doing the show/hide of the logo? Or maybe just not show the logo on mobile at all?

**Comment by budparr** [comment]
I'll look, but my guess is that you're right that we shouldn't do it on mobile.

**Comment by budparr** [comment]
that's better. A few items:

- [x] Now the support us button is missing altogether. It should be in the content.
- [x] The support us button appearance in the sticky nav is a bit janky (as all the others, but less so). 
- [x] The highlighted items are off. When I click on Impact & Awards, the Partner's button is highlighted (see image).
- [x] Targets still off for me (see same image)
- [x] This might have been something I screwed up, but the menu items on the main about page are correct (impact & awards, partners, staff, supporters, mission), but on interior pages, they should be in the same order (always) and they're not.

<img width="1019" alt="Screen Shot 2022-05-31 at 11 27 26 AM" src="https://user-images.githubusercontent.com/115347/171211270-cad5cf9e-6dc8-420f-a0f0-d2fc9fc492f4.png">

**Comment by AdamChlan** [comment]
Have most of this cleaned up...looking into what's going with the first two menu items not showing as active when scrolled to

**Comment by AdamChlan** [comment]
@regisphilibert I'm a bit stumped on this one:

`The highlighted items are off. When I click on Impact & Awards, the Partner's button is highlighted (see image).`

Seems like the first two menu items don't receive an active state. When I output the ID of them, it seems right to me. Mind taking a look?

**Comment by AdamChlan** [comment]
I pushed up an adjustment to the intersect setting, but I also had to add a bit more teaser content to the various anchored sections. If two sections appear on the screen, the second one is going to take president and be considered the active section. We may need to adjust this once we know the actual content that will appear in the sections.

**Comment by budparr** [comment]
So much better, thank you. Couple things: 

- [x] "Supporters" link on the main about page still highlights "Mission"
- [x] Anyway to make the transition a bit smoother/slower when we go to sticky nav? I think it's the insertion of the logo.

**Comment by AdamChlan** [comment]
@budparr I slowed down he transition, and made the logo removal smoother. For the highlighted nav, unfortunately it's a bit of moving target based on the amount of content in each section, and screens size. We may need to explore a different tech for this. I can see if there are any viable alternatives.

**Comment by AdamChlan** [comment]
@budparr I set a minimum height for the sections, so the menu highlighting is working more reliably now.
