### ISSUE TITLE
Align block headings as per mockup

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#14]
I'm using `transform: rotate(-90deg);` to accomplish this, so with that we just need to position the heading.

<img width="403" alt="Screen Shot 2022-06-03 at 5 17 41 PM" src="https://user-images.githubusercontent.com/115347/171955075-a181d6c1-4949-42de-a400-c8e4fd5d5912.png">

**Comment by AdamChlan** [comment]
@budparr I pushed up a fix for this.
