### ISSUE TITLE
Have internal about pages contextual menu reflect parent (about-tnd)

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#16]

**Comment by regisphilibert** [comment]
Let me know when you pushed your changes and I'll fix that real quick for you.

**Comment by budparr** [comment]
My changes are pushed.

Just noting for posterity that this solution of linking to blocks on the main page and then linking to pages on interior pages that look the same is ripe for errors. No action necessary, what we have is the best solution at the moment.

**Comment by regisphilibert** [comment]
> Just noting for posterity that this solution of linking to blocks on the main page and then linking to pages on interior pages that look the same is ripe for errors.

My feeling also.

**Comment by regisphilibert** [comment]
I pushed on the branch.
