### ISSUE TITLE
Update Spotlight hero  Edit

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#2]
Update hero as per image, except we'll need more spacing, so leave that closer to what's there now and I'll tighten it up, if needed.

https://www.figma.com/file/G8essVjeMul3J5mKoxCMQF/spotlightpa-(INTERNAL)?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/115347/169534905-c3ef5498-592c-49a0-9379-bdf77d52aa8d.png)

**Comment by AdamChlan** [comment]
@budparr I have pushed up changes for this on our working branch. Let me know if you need anything else further.
