### ISSUE TITLE
Fill out Socials with icons (inline Icon followed by name of network)

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#5]
- use the icons we use in our module
- Make the icons inline with social name next to them to the right

**Comment by budparr** [comment]
@AdamChlan I think this is the only thing missing now before I send to client.

**Comment by AdamChlan** [comment]
@regisphilibert let's chat about this one

**Comment by AdamChlan** [comment]
@budparr this is in place

**Comment by budparr** [comment]
Thanks!
