### ISSUE TITLE
Make hero list of topics conditional on location

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/spotlightpa.org#6]
Hide on Home page (I think!, it could be only show on home page). If Régis doesn't remember I'll double check and ask client if needed.

**Comment by budparr** [comment]
@regisphilibert we have this in place, is that right?

**Comment by regisphilibert** [comment]
No actually we have nothing in place, so we would only show this whole part (which I call hero) on certain pages based on a front matter field?

**Comment by budparr** [comment]
From what I recall of our meeting, they don't want the topics on the home page, but I think your instinct is right to make it based on a front-matter field. Something like `show-topics: false` and otherwise show them.

**Comment by budparr** [comment]
I wasn't clear about this. The topics need to be hidden on some pages, not the whole hero. I'll see if I can fix it myself.

**Comment by budparr** [comment]
Pretty straightforward. I need to show all the topics in the dropdown if they are not in the hero. This is what I'm using:





was
```
{{ $other_topics = symdiff $first_topics $all_topics }}
```
I changed to

```
{{ $other_topics := "" }}
{{ if not .Params.disable_hero }}
  {{ $other_topics = symdiff $first_topics $all_topics }}
{{ else }}  
  {{ $other_topics = $all_topics }}  
{{ end }}
```

Look right? seems to work, but worth checking

**Comment by regisphilibert** [comment]
Yes if it looks good! And now I understand what was asked here :)
